version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./src:/src
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        depends_on:
            - php
    
    php:
        image: php:8.0.6-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./src:/src
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql-db
        depends_on:
            - mysql-db
        networks:
            - app-network

    mysql-db:
        image: mysql:8.0.25
        container_name: mysql-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "pizzapie123"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge